name: Format Codebase

permissions:
  contents: write  
  workflows: write

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Format Project
        run: bunx prettier --write .

      - name: Commit and Push Changes
        continue-on-error: true
        run: |
          git add .
          git commit -m "chore: auto format" || echo "No changes to commit"
          git push

      - name: Ensure Workflow Exit
        run: exit 0